name: Package GEDKeeper3 for MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  mac:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -p:Configuration=Release -p:Platform=MacOS -p:EnableDmgBuild=true
      working-directory: projects/GKv3
    - name: Upload DMG file
      uses: actions/upload-artifact@v3
      with:
        name: GEDKeeper3
        path: projects/GKv3/GEDKeeper3/bin/Debug/MacOS/*.dmg
        if-no-files-found: error
